// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHVRpE8hGurx73rfAlCQV5e_TRPwXnTlk',
    appId: '1:808749677810:web:d07f65aabcb64c0145246b',
    messagingSenderId: '808749677810',
    projectId: 'diginifi',
    authDomain: 'diginifi.firebaseapp.com',
    storageBucket: 'diginifi.appspot.com',
    measurementId: 'G-XPF8YX4HFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOWgxvj_LaM5TRuZhddcksFr-8LzTmXo',
    appId: '1:808749677810:android:57e3f234faf84ed545246b',
    messagingSenderId: '808749677810',
    projectId: 'diginifi',
    storageBucket: 'diginifi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL65yudkM7MsucRQDQN4dzVi3dRrxdsko',
    appId: '1:808749677810:ios:d3138e0ad5d9bf2545246b',
    messagingSenderId: '808749677810',
    projectId: 'diginifi',
    storageBucket: 'diginifi.appspot.com',
    iosBundleId: 'com.app.reentryroadmap',
  );

}